version: '3'
services:
  mysqldatabase:
    image: mysql:5.7.22
    restart: always
    ports:
      - "33066:3306"
    env_file:
      - db.env
    volumes:
      - .dbdata:/var/lib/mysql

  backend:
    stdin_open: true
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - 'mysqldatabase'
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app

  ng:
    stdin_open: true
    container_name: ng
    build:
      context: frontend
      dockerfile:  Dockerfile
    volumes:
    - ./frontend:/web